export const post_starwars_canada = [
    {key: 'strongwars', slide: 1, region: 'BC', from: 'wars', text: 'Star Wars est nettement meilleur que Star Trek. Ce n\'est même pas proche. Star Trek a des efforts visuels minables, une vision idéaliste ridicule de l\'humanité, et rien d\'amusant. Star Wars est le monde réel sale et brutal. Star Trek est juste pour les nerds qui ne peuvent pas faire face à la réalité.'},
    {key: 'weakwars', slide: 2, region: 'BC', from: 'boring', text: "Star Wars est la meilleure émission, mais Star Trek a certainement eu son moment. Star Wars a un univers beaucoup plus riche, et s'est clairement enfoncé plus profondément dans notre culture, mais Star Trek nous a donné des personnages comme Spock, des idées comme la téléportation, et l'emblématique USS Enterprise"},
    {key: 'complicated', slide: 3, region: 'QC', from: 'peacemaker', text: "Je pense qu'ils sont tous les deux de grands spectacles, mais pour des raisons différentes. Star Wars est plus un opéra de l'espace, tandis que Star Trek est plus un spectacle de science-fiction. Je pense que cela dépend de ce que vous recherchez dans un spectacle. Si vous voulez de l'action et de l'aventure, alors Star Wars est la voie à suivre. Si vous voulez explorer la condition humaine et l'avenir de l'humanité, alors Star Trek est la voie à suivre."},
    {key: 'alsocomplicated', slide: 3, region: 'QC', from: 'new', text: "Star Trek est meilleur à regarder, et je pense aussi meilleur pour l'humanité. J'aime l'optimisme de l'humanité qui s'étend au-delà des planètes, se lie d'amitié avec d'autres espèces et résout des problèmes. J'aime comment les épisodes touchent à des problèmes sociaux importants qui s'appliquent aujourd'hui. Mais Star Wars a certainement sa place. Le style visuel est inégalé, et des personnages comme Dark Vador et Yoda sont emblématiques."},
    {key: 'strongtreky', slide: 5, region: 'ON', from: 'trek', text: "Pourquoi avons-nous même cette discussion. Star Trek est si moralement corrompu que c'est irréel. C'est le spectacle préféré d'Osama Bin Lader. Le point culminant est la destruction d'une 'Étoile de la Mort' qui abritait des millions de personnes. Star Wars est pour les moralement dépravés. Star Trek, d'autre part, est une belle exploration de la nature de la moralité, en utilisant l'espace comme toile de fond."}
]

export const post_starwars_france = [
    {key: 'strongwars', slide: 1, region: 'ARA', from: 'wars', text: 'Star Wars est nettement meilleur que Star Trek. Ce n\'est même pas proche. Star Trek a des efforts visuels minables, une vision idéaliste ridicule de l\'humanité, et rien d\'amusant. Star Wars est le monde réel sale et brutal. Star Trek est juste pour les nerds qui ne peuvent pas faire face à la réalité.'},
    {key: 'weakwars', slide: 2, region: 'ARA', from: 'boring', text: "Star Wars est la meilleure émission, mais Star Trek a certainement eu son moment. Star Wars a un univers beaucoup plus riche, et s'est clairement enfoncé plus profondément dans notre culture, mais Star Trek nous a donné des personnages comme Spock, des idées comme la téléportation, et l'emblématique USS Enterprise"},
    {key: 'complicated', slide: 3, region: 'GES', from: 'peacemaker', text: "Je pense qu'ils sont tous les deux de grands spectacles, mais pour des raisons différentes. Star Wars est plus un opéra de l'espace, tandis que Star Trek est plus un spectacle de science-fiction. Je pense que cela dépend de ce que vous recherchez dans un spectacle. Si vous voulez de l'action et de l'aventure, alors Star Wars est la voie à suivre. Si vous voulez explorer la condition humaine et l'avenir de l'humanité, alors Star Trek est la voie à suivre."},
    {key: 'alsocomplicated', slide: 3, region: 'NOR', from: 'new', text: "Star Trek est meilleur à regarder, et je pense aussi meilleur pour l'humanité. J'aime l'optimisme de l'humanité qui s'étend au-delà des planètes, se lie d'amitié avec d'autres espèces et résout des problèmes. J'aime comment les épisodes touchent à des problèmes sociaux importants qui s'appliquent aujourd'hui. Mais Star Wars a certainement sa place. Le style visuel est inégalé, et des personnages comme Dark Vador et Yoda sont emblématiques."},
    {key: 'strongtreky', slide: 5, region: 'NOR', from: 'trek', text: "Pourquoi avons-nous même cette discussion. Star Trek est si moralement corrompu que c'est irréel. C'est le spectacle préféré d'Osama Bin Lader. Le point culminant est la destruction d'une 'Étoile de la Mort' qui abritait des millions de personnes. Star Wars est pour les moralement dépravés. Star Trek, d'autre part, est une belle exploration de la nature de la moralité, en utilisant l'espace comme toile de fond."}
]

