
export const post_starwars_german = [
    {key: 'strongwars', slide: 1, region: 'BE', from: 'b', text: 'Star Wars ist weitaus besser als Star Trek. Es ist nicht mal annähernd. Star Trek hat schlechte visuelle Effekte, eine lächerlich idealistische Sicht auf die Menschheit und nichts Spaßiges. Star Wars ist die schmutzige, echte Welt. Star Trek ist nur für Nerds, die nicht mit der Realität klarkommen.'},
    {key: 'weakwars', slide: 2, region: 'BE', from: 'b', text: "Star Wars ist die bessere Show, aber Star Trek hatte definitiv seinen Moment. Star Wars hat ein viel reicheres Universum und hat sich klar tiefer in unserer Kultur verankert, aber Star Trek hat uns Charaktere wie Spock, Ideen wie Teleportation und die ikonische USS Enterprise gebracht"},
    {key: 'complicated', slide: 3, region: 'SN', from: 'f', text: "Ich denke, sie sind beide großartige Shows, aber aus unterschiedlichen Gründen. Star Wars ist mehr eine Weltraum-Oper, während Star Trek mehr eine Science-Fiction-Show ist. Es kommt darauf an, was Sie in einer Show suchen. Wenn Sie Action und Abenteuer wollen, dann ist Star Wars der Weg. Wenn Sie den Zustand der Menschheit und die Zukunft der Menschheit erkunden wollen, dann ist Star Trek der Weg."},
    {key: 'alsocomplicated', slide: 3, region: 'BW', from: 'e', text: "Star Trek ist besser anzusehen, und ich denke auch besser für die Menschheit. Ich liebe die optimistische Sicht der Menschheit, die sich über die Planeten hinaus ausbreitet, sich mit anderen Spezies anfreundet und Probleme löst. Ich liebe, wie die Episoden wichtige soziale Themen berühren, die heute gelten. Aber Star Wars hat definitiv seinen Platz. Der visuelle Stil ist unübertroffen und Charaktere wie Darth Vader und Yoda sind ikonisch."},
    {key: 'strongtreky', slide: 5, region: 'NW', from: 'c', text: "Warum haben wir überhaupt diese Diskussion. Star Trek ist so moralisch korrupt, dass es unrealistisch ist. Es ist die Lieblingsshow von Osama Bin Lader. Der Höhepunkt ist die Zerstörung eines 'Todessterns', der Millionen von Menschen beherbergte. Star Wars ist für die moralisch Verdorbenen. Star Trek hingegen ist eine wunderschöne Erforschung der Natur der Moral, mit dem Weltraum als Kulisse."}
]

